In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("./students.csv")
df.head()

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
1,2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000
2,3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
3,4,Tamim Hossain,Male,BBA,Dhaka,23,2.95,72.0,10.0,No,55000
4,5,Nabila Akter,Female,CSE,Rajshahi,21,3.66,90.0,20.0,Yes,65000

In [9]:
df2 = pd.read_csv("./students.csv", index_col="student_id")
df2.head()

,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
student_id,,,,,,,,,,
1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000
3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
4,Tamim Hossain,Male,BBA,Dhaka,23,2.95,72.0,10.0,No,55000
5,Nabila Akter,Female,CSE,Rajshahi,21,3.66,90.0,20.0,Yes,65000

In [10]:
df.tail()

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
22,23,Jarin Tasnim,Female,EEE,Dhaka,21,3.70,88.0,20.0,Yes,70000
23,24,Rakib Hasan,Male,CSE,Sylhet,22,3.35,79.0,15.0,No,65000
24,25,Mehedi Hasan,Male,BBA,Barishal,24,2.60,NaN,7.0,No,55000
25,26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000
26,27,Sohel Rana,Male,ME,Chattogram,23,3.00,69.0,NaN,No,60000

In [11]:
print(df.tail(3))

    student_id          name  gender department        city  age  cgpa  \
24          25  Mehedi Hasan    Male        BBA    Barishal   24  2.60
25          26  Ishrat Jahan  Female        CSE       Dhaka   20  3.85
26          27    Sohel Rana    Male         ME  Chattogram   23  3.00

    attendance  study_hour scholarship  tuition_fee
24         NaN         7.0          No        55000
25        92.0        24.0         Yes        65000
26        69.0         NaN          No        60000

In [12]:
df.shape

(27, 11)

In [13]:
df2.shape

(27, 10)

In [15]:
print(df.columns)

Index(['student_id', 'name', 'gender', 'department', 'city', 'age', 'cgpa',
       'attendance', 'study_hour', 'scholarship', 'tuition_fee'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   27 non-null     int64
 1   name         27 non-null     str
 2   gender       27 non-null     str
 3   department   27 non-null     str
 4   city         27 non-null     str
 5   age          27 non-null     int64
 6   cgpa         25 non-null     float64
 7   attendance   26 non-null     float64
 8   study_hour   26 non-null     float64
 9   scholarship  27 non-null     str
 10  tuition_fee  27 non-null     int64
dtypes: float64(3), int64(3), str(5)
memory usage: 2.4 KB

In [18]:
df.describe()

       student_id        age       cgpa  attendance  study_hour   tuition_fee
count   27.000000  27.000000  25.000000   26.000000   26.000000     27.000000
mean    14.000000  21.629630   3.450400   81.769231   17.038462  62629.629630
std      7.937254   1.418237   0.393589   10.096763    6.043051   5175.000172
min      1.000000  19.000000   2.600000   65.000000    7.000000  55000.000000
25%      7.500000  20.500000   3.200000   72.500000   12.250000  59000.000000
50%     14.000000  22.000000   3.500000   83.000000   16.500000  65000.000000
75%     20.500000  23.000000   3.780000   89.750000   21.750000  65000.000000
max     27.000000  24.000000   3.990000   98.000000   28.000000  70000.000000

In [20]:
print(df["name"])

0      Ayesha Rahman
1        Karim Uddin
2        Sadia Islam
3      Tamim Hossain
4       Nabila Akter
5          Rahim Mia
6     Farhana Yasmin
7         Imran Khan
8      Sumaiya Begum
9        Jahid Hasan
10    Mitu Chowdhury
11       Rifat Ahmed
12     Lamia Sultana
13    Shakib Al Amin
14      Nusrat Jahan
15        Fahim Reza
16       Tania Haque
17      Sabbir Ahmed
18       Rima Khatun
19      Arif Hossain
20     Sharmin Akter
21      Nayeem Islam
22      Jarin Tasnim
23       Rakib Hasan
24      Mehedi Hasan
25      Ishrat Jahan
26        Sohel Rana
Name: name, dtype: str

In [21]:
print(type(df.name))

<class 'pandas.Series'>

In [22]:
print(df["name"].head())

0    Ayesha Rahman
1      Karim Uddin
2      Sadia Islam
3    Tamim Hossain
4     Nabila Akter
Name: name, dtype: str

In [25]:
df[["name", "cgpa"]].head()

            name  cgpa
0  Ayesha Rahman  3.92
1    Karim Uddin  3.45
2    Sadia Islam  3.78
3  Tamim Hossain  2.95
4   Nabila Akter  3.66

### Selection Rows --- loc (work with label) and iloc(work with position/index)

In [62]:
df.loc[0]

student_id                 1
name           Ayesha Rahman
gender                Female
department               CSE
city                   Dhaka
age                       21
cgpa                    3.92
attendance              95.0
study_hour              25.0
scholarship              Yes
tuition_fee            65000
Name: 0, dtype: object

In [27]:
df.iloc[0]

student_id                 1
name           Ayesha Rahman
gender                Female
department               CSE
city                   Dhaka
age                       21
cgpa                    3.92
attendance              95.0
study_hour              25.0
scholarship              Yes
tuition_fee            65000
Name: 0, dtype: object

In [28]:
df.loc[4:10]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
4,5,Nabila Akter,Female,CSE,Rajshahi,21,3.66,90.0,20.0,Yes,65000
5,6,Rahim Mia,Male,ME,Khulna,22,3.10,68.0,12.0,No,60000
6,7,Farhana Yasmin,Female,EEE,Dhaka,20,3.88,93.0,24.0,Yes,70000
7,8,Imran Khan,Male,BBA,Chattogram,24,3.25,78.0,14.0,No,55000
8,9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
9,10,Jahid Hasan,Male,ME,Sylhet,23,2.70,65.0,8.0,No,60000
10,11,Mitu Chowdhury,Female,EEE,Rajshahi,21,3.55,85.0,18.0,No,70000

In [30]:
df.iloc[0:5, 1:3]

            name  gender
0  Ayesha Rahman  Female
1    Karim Uddin    Male
2    Sadia Islam  Female
3  Tamim Hossain    Male
4   Nabila Akter  Female

In [35]:
df.loc[df["cgpa"] >3.9]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
8,9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
20,21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000

In [37]:
df.loc[df["cgpa"] >3.9,["name", "cgpa"]]

             name  cgpa
0   Ayesha Rahman  3.92
8   Sumaiya Begum  3.99
20  Sharmin Akter  3.95

### and or not -> & | !

In [38]:
df[df["cgpa"]>3.8]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
6,7,Farhana Yasmin,Female,EEE,Dhaka,20,3.88,93.0,24.0,Yes,70000
8,9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
14,15,Nusrat Jahan,Female,CSE,Dhaka,21,3.81,91.0,23.0,Yes,65000
20,21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
25,26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000

In [39]:
df[(df["cgpa"]>3.8) & (df["department"]=="CSE")]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
8,9,Sumaiya Begum,Female,CSE,Dhaka,19,3.99,98.0,28.0,Yes,65000
14,15,Nusrat Jahan,Female,CSE,Dhaka,21,3.81,91.0,23.0,Yes,65000
20,21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
25,26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000

In [42]:
df.loc[df["student_id"]==9,"age"] = 25

In [43]:
df[df["student_id"]==9]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
8,9,Sumaiya Begum,Female,CSE,Dhaka,25,3.99,98.0,28.0,Yes,65000

In [44]:
df.head()

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
1,2,Karim Uddin,Male,EEE,Chattogram,22,3.45,80.0,15.0,No,70000
2,3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
3,4,Tamim Hossain,Male,BBA,Dhaka,23,2.95,72.0,10.0,No,55000
4,5,Nabila Akter,Female,CSE,Rajshahi,21,3.66,90.0,20.0,Yes,65000

In [47]:
df[(df["city"]=="Sylhet") | (df["city"]=="Khulna") ]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
2,3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
5,6,Rahim Mia,Male,ME,Khulna,22,3.10,68.0,12.0,No,60000
9,10,Jahid Hasan,Male,ME,Sylhet,23,2.70,65.0,8.0,No,60000
13,14,Shakib Al Amin,Male,ME,Khulna,24,3.05,70.0,11.0,No,60000
16,17,Tania Haque,Female,EEE,Sylhet,20,3.60,87.0,19.0,No,70000
20,21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
23,24,Rakib Hasan,Male,CSE,Sylhet,22,3.35,79.0,15.0,No,65000

In [52]:
df[df["city"].isin(["Sylhet","Khulna"])]

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
2,3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000
5,6,Rahim Mia,Male,ME,Khulna,22,3.10,68.0,12.0,No,60000
9,10,Jahid Hasan,Male,ME,Sylhet,23,2.70,65.0,8.0,No,60000
13,14,Shakib Al Amin,Male,ME,Khulna,24,3.05,70.0,11.0,No,60000
16,17,Tania Haque,Female,EEE,Sylhet,20,3.60,87.0,19.0,No,70000
20,21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
23,24,Rakib Hasan,Male,CSE,Sylhet,22,3.35,79.0,15.0,No,65000

In [57]:
df.sort_values("cgpa",ascending=False )   .head(7)

,student_id,name,gender,department,city,age,cgpa,attendance,study_hour,scholarship,tuition_fee
8,9,Sumaiya Begum,Female,CSE,Dhaka,25,3.99,98.0,28.0,Yes,65000
20,21,Sharmin Akter,Female,CSE,Khulna,20,3.95,96.0,27.0,Yes,65000
0,1,Ayesha Rahman,Female,CSE,Dhaka,21,3.92,95.0,25.0,Yes,65000
6,7,Farhana Yasmin,Female,EEE,Dhaka,20,3.88,93.0,24.0,Yes,70000
25,26,Ishrat Jahan,Female,CSE,Dhaka,20,3.85,92.0,24.0,Yes,65000
14,15,Nusrat Jahan,Female,CSE,Dhaka,21,3.81,91.0,23.0,Yes,65000
2,3,Sadia Islam,Female,CSE,Sylhet,20,3.78,88.0,22.0,Yes,65000

### EDA -- Exploratory Data Analysis

In [59]:
df["department"].value_counts()

department
CSE      10
EEE       5
BBA       5
ME        5
Civil     2
Name: count, dtype: int64

In [60]:
df["department"].unique()

<StringArray>
['CSE', 'EEE', 'BBA', 'ME', 'Civil']
Length: 5, dtype: str

In [61]:
df.isnull().sum()

student_id     0
name           0
gender         0
department     0
city           0
age            0
cgpa           2
attendance     1
study_hour     1
scholarship    0
tuition_fee    0
dtype: int64

In [64]:
print(df.loc[df["department"]=="CSE", "cgpa"].isnull().sum())

1